DROP DATABASE IF EXISTS PSP;
CREATE DATABASE IF NOT EXISTS PSP CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;
USE PSP;

DROP TABLE IF EXISTS People;
CREATE TABLE IF NOT EXISTS People(
    idPeople INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    cF CHAR(16) UNIQUE NOT NULL,
    gender CHAR(1) NOT NULL DEFAULT 'm',
    email VARCHAR(100) UNIQUE NOT NULL,
    birthday DATE NOT NULL,
    sub VARCHAR(24),
    idClass INT REFERENCES Classm(IdClass)
);

DROP TABLE IF EXISTS Classm;
CREATE TABLE IF NOT EXISTS Classm(
    idClass INT PRIMARY KEY AUTO_INCREMENT,
    carrel VARCHAR(2) NOT NULL,
    year INT NOT NULL,
    articulation VARCHAR(30) NOT NULL,
    active VARCHAR(3) DEFAULT "YES" NOT NULL
);

DROP TABLE IF EXISTS Phones;
CREATE TABLE IF NOT EXISTS Phones(
	idPhones INT PRIMARY KEY AUTO_INCREMENT,
    number VARCHAR(15) NOT NULL UNIQUE,
    prefix VARCHAR(5) NOT NULL,
    idPeople INT UNIQUE NOT NULL REFERENCES People(IdPeople) 
);

DROP TABLE IF EXISTS Vehicles;
CREATE TABLE IF NOT EXISTS Vehicles(
    idV INT PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(8) NOT NULL,
    plate VARCHAR(8) UNIQUE NOT NULL,
    owner VARCHAR(70) NOT NULL,
    idPeople INT NOT NULL REFERENCES People(IdPeople) 
);

DROP TABLE IF EXISTS Account;
CREATE TABLE IF NOT EXISTS Account(
    idAccount  INT PRIMARY KEY AUTO_INCREMENT,
    nick VARCHAR(24) UNIQUE NOT NULL,
    p_ass CHAR(128) NOT NULL,
    gK CHAR(4) UNIQUE NOT NULL,
    ruolo VARCHAR(12) NOT NULL,
    dataReg DATE NOT NULL,
    dataExp DATE,
    valid CHAR(1) DEFAULT 'F', 
    idPeople INT UNIQUE REFERENCES People(IdPeople) 
);

INSERT INTO Account(nick, p_ass, gK, ruolo, dataReg, valid) VALUES 
    ('Admin', SHA2('admin', 256), '0000', 'Admin', CURRENT_DATE, 'O');

DROP TABLE IF EXISTS Entries;
CREATE TABLE IF NOT EXISTS Entries(
    idIng INT PRIMARY KEY AUTO_INCREMENT,
    dataIn DATETIME NOT NULL,
    dataOut DATETIME,
    idAccount INT NOT NULL REFERENCES Account(IdAccount)
);
